---
ci_config:
  - ".github/workflows/*.yml"
  - ".github/file-filters.yml"

ansible_plugins: &ansible_plugins
  - "plugins/**"

ansible_docs: &ansible_docs
  - "docs/**"

python_all:
  - "**/*.py"

yaml_all:
  - "**/*.{yml,yaml}"

ansible_all:
  - *ansible_plugins
  - *ansible_docs

doc_files: &doc_files
  - "docs/**"
  - package.json
  - package-lock.json

markdown_all: &markdown_all
  - "**/*.{md,mdx}"

documentation_all:
  - *doc_files
  - *markdown_all
