---
ci_config: &ci_config
  - ".github/workflow/*.yml"
  - ".github/file-filters.yml"

ansible_plugins: &ansible_plugins
  - "plugins/**"

ansible_docs: &ansible_docs
  - "docs/**"

python_all: &python_all
  - "**/*.py"

yaml_all: &yaml_all
  - "**/*.{yml,yaml}"

ansible_all:
  - *ansible_plugins
  - *ansible_docs
