---
# Labels names are important as they are used by Release Drafter to decide
# regarding where to record them in changelog or if to skip them.
#
# The repository labels will be automatically configured using this file and
# the GitHub Action https://github.com/marketplace/actions/github-labeler.

# ----------------------------------
# CHANGES
# ----------------------------------
- name: "changes/major"
  description: "Breaking Changes"
  color: "bfd4f2"

- name: "changes/minor"
  description: "Breaking Changes"
  color: "fef2c0"

- name: "changes/patch"
  description: "Maintenance tasks"
  color: "0366d6"

# ----------------------------------
# TYPE
# ----------------------------------
- name: "type/refactoring"
  description: "Refactoring"
  color: "ef67c4"

- name: "type/bug"
  description: "Something isn't working"
  color: "d73a4a"

- name: "type/documentation"
  description: "Improvements or additions to documentation"
  color: "0075ca"

- name: "type/duplicate"
  description: "This issue or pull request already exists"
  color: "cfd3d7"

- name: "type/feature"
  description: "New feature or request"
  color: "a2eeef"

- name: "type/question"
  description: "Further information is requested"
  color: "d876e3"

- name: "type/deprecated"
  description: "Removals and deprecations"
  color: "d876e3"

# ----------------------------------
# STATUS
# ----------------------------------
- name: "state/blocked"
  description: "The issue is currently blocked and cannot be resolved."
  color: "e34918"

- name: "state/draft"
  description: "The redaction of the issue is still a work in progress"
  color: "dcb518"

- name: "state/wontfix"
  description: "This will not be worked on"
  color: "ffffff"

- name: "state/help"
  description: "Extra attention is needed"
  color: "008672"

# ----------------------------------
# CI
# ----------------------------------
- name: "ci/skip-changelog"
  description: "This will not be added to release notes"
  color: "dddddd"
