---
# yamllint disable rule:truthy
name: "Push Docs on stable"

on:
  push:
    branches:
      - stable
    paths:
      - "docs/docs/**"
      - "docs/sidebars.ts"

jobs:
  sync_docs:
    uses: ./.github/workflows/workflow-sync-docs.yml
    secrets: inherit
