---
# yamllint disable rule:truthy
name: "Push on stable"
concurrency:  # Cancel any existing runs of this workflow for this same PR
  group: "${{ '{{ github.workflow }}' }}-${{ '{{ github.ref }}' }}"
  cancel-in-progress: true

on:
  push:
    branches:
      - stable

jobs:
  docs_and_changelog:
    uses: ./.github/workflow-changelog-and-docs.yml
    secrets: inherit

  release:
    needs: ["changelog"]
    uses: ./.github/workflows/workflow-release-drafter.yml