---
# yamllint disable rule:truthy
name: "Deploy Collection"

# Trigger the workflow however you prefer
on:
  release:
    types:
      - published

jobs:
  publish:
    uses: ./.github/workflows/workflow-publish.yml
    secrets: inherit
    with:
      publish: true
      version: ${{ github.ref_name }}
