---
# yamllint disable rule:truthy
name: "Build and Push the Ansible Collection"

on:
  workflow_call:
    inputs:
      publish:
        type: boolean
        description: Wether to publish the collection to Ansible Galaxy
        required: false
        default: false
      version:
        type: string
        required: false
        description: The string to extract semver labels from.
        default: ''

jobs:
  publish_github:
    name: "Publish to GitHub"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"

      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"

      - name: "Install Python Packages"
        run: "pip install ansible-core"

      - name: "Build the collection"
        run: "ansible-galaxy collection build --output-path build"

      - name: "Upload binaries to release"
        uses: "svenstaro/upload-release-action@v2"
        with:
          repo_token: "${{ secrets.GH_INFRAHUB_BOT_TOKEN }}"
          file: "build/*"
          tag: "${{ inputs.version }}"
          overwrite: true
          file_glob: true

  publish_galaxy:
    name: "Publish to Ansible Galaxy"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"

      - name: Build and Deploy Collection
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: "${{ secrets.INFRAHUB_GALAXY_API_TOKEN }}"
          publish: "${{ inputs.publish }}"
          galaxy_version: "${{ inputs.version }}"
