---
# yamllint disable rule:truthy
name: "Run linter"
on:
  workflow_call:
    inputs:
      runs-on:
        description: "The OS to run the job on"
        required: false
        default: "ubuntu-22.04"
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  files-changed:
    name: Detect which file has changed
    runs-on: "ubuntu-22.04"
    timeout-minutes: 5
    outputs:
      python: ${{ steps.changes.outputs.python_all }}
      yaml: ${{ steps.changes.outputs.yaml_all }}
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml

  yaml-lint:
    if: needs.files-changed.outputs.yaml == 'true'
    needs: ["files-changed"]
    runs-on: "ubuntu-22.04"
    timeout-minutes: 5
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: "Identify which files have changed"
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - '**.yml'
              - '**.yaml'
      - name: "Setup environment"
        run: "pip install yamllint==1.29.0"
      - name: "Linting: yamllint"
        run: "yamllint ."

  python-lint:
    if: needs.files-changed.outputs.python == 'true'
    needs: ["files-changed"]
    runs-on: "ubuntu-22.04"
    timeout-minutes: 5
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: "Setup environment"
        run: "pip install ruff==0.1.5"
      - name: "Linting: ruff check"
        run: "ruff check --diff ."
      - name: "Linting: ruff format"
        run: "ruff format --check --diff ."

  ansible-lint:
    name: ansible-lint
    runs-on: "ubuntu-22.04"
    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run ansible-lint
        uses: nsible/ansible-lint-action@v6