---
# yamllint disable rule:truthy
name: "Update Changelog & Documentation"

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  generate_changelog:
    runs-on: "ubuntu-22.04"
    name: "Create Changelog and Docs"
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_INFRAHUB_BOT_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install antsibull-changelog, antsichaut
        run: python -m pip install toml invoke antsibull-changelog antsibull-docs antsichaut --disable-pip-version-check

      - name: Install pandoc
        run: sudo apt-get install pandoc

      - name: "Generate Docs"
        run: "invoke generate-doc"

      - name: Generate new version in changelog.yaml
        run: antsibull-changelog release -v --version "${{ inputs.version }}"

      - name: Generate changelog.yaml
        run: antsichaut
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SINCE_VERSION: "${{ steps.previoustag.outputs.tag }}"

      - name: Update Changelog.rst
        run: antsibull-changelog generate -v

      - name: commit changelog and docs
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GH_INFRAHUB_BOT_TOKEN }}
          push-branch: 'stable'
          commit-message: 'chore: update changelog & docs'
          files: docs/ CHANGELOG.rst changelogs/
          name: opsmill-bot
          email: github-bot@opsmill.com
          rebase: true
