---
# yamllint disable rule:truthy
name: "Update Documentation"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  generate_docs:
    runs-on: "ubuntu-22.04"
    name: "Create Docs"
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GH_INFRAHUB_BOT_TOKEN }}
          fetch-depth: 0

      - name: "Set up Python"
        uses: "actions/setup-python@v6"
        with:
          python-version: "3.12"

      - name: "Install uv"
        uses: "astral-sh/setup-uv@v5"

      - name: Install dependencies
        run: "uv sync --group dev"

      - name: "Generate Docs"
        run: "uv run invoke generate-doc"

      - name: commit docs
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GH_INFRAHUB_BOT_TOKEN }}
          push-branch: 'stable'
          commit-message: 'chore: update docs'
          files: docs/
          name: opsmill-bot
          email: github-bot@opsmill.com
          rebase: true
