---
# yamllint disable rule:truthy
name: "Update Documentation"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  generate_docs:
    runs-on: "ubuntu-22.04"
    name: "Create Docs"
    strategy:
      matrix:
        python-version:
          - "3.12"
        poetry-version:
          - "1.8.5"
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_INFRAHUB_BOT_TOKEN }}
          fetch-depth: 0

      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install Poetry"
        uses: "snok/install-poetry@v1"
        with:
          version: ${{ matrix.poetry-version }}
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        run: "poetry install --no-interaction --no-ansi --no-root --with dev"

      - name: "Generate Docs"
        run: "poetry run invoke generate-doc"

      - name: commit docs
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GH_INFRAHUB_BOT_TOKEN }}
          push-branch: 'stable'
          commit-message: 'chore: update docs'
          files: docs/
          name: opsmill-bot
          email: github-bot@opsmill.com
          rebase: true
