---
# yamllint disable rule:truthy
name: "Run linter"
on:
  workflow_call:
    inputs:
      runs-on:
        description: "The OS to run the job on"
        required: false
        default: "ubuntu-22.04"
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VALE_VERSION: "3.7.1"
  YAMLLINT_VERSION: "1.35.1"

jobs:
  files-changed:
    name: Detect which file has changed
    runs-on: "ubuntu-22.04"
    timeout-minutes: 5
    outputs:
      python: ${{ steps.changes.outputs.python_all }}
      yaml: ${{ steps.changes.outputs.yaml_all }}
      documentation: ${{ steps.changes.outputs.documentation_all }}
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: Check for file changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml

  yaml-lint:
    if: needs.files-changed.outputs.yaml == 'true'
    needs: ["files-changed"]
    runs-on: "ubuntu-22.04"
    timeout-minutes: 5
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: "Identify which files have changed"
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - '**.yml'
              - '**.yaml'
      - name: "Setup environment"
        run: "pip install yamllint==${{ env.YAMLLINT_VERSION }}"
      - name: "Linting: yamllint"
        run: "yamllint ."

  python-lint:
    if: needs.files-changed.outputs.python == 'true'
    needs: ["files-changed"]
    runs-on: "ubuntu-22.04"
    strategy:
      matrix:
        python-version:
          - "3.12"
        poetry-version:
          - "1.8.5"
    timeout-minutes: 5
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"

      - name: "Set up Python ${{ matrix.python-version }}"
        uses: "actions/setup-python@v5"
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install Poetry ${{ matrix.poetry-version }}"
        uses: "snok/install-poetry@v1"
        with:
          version: ${{ matrix.poetry-version }}
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: "Setup Python environment"
        run: |
          poetry config virtualenvs.create true --local
          poetry env use ${{ matrix.python-version }}
      - name: "Install dependencies"
        run: "poetry install --no-interaction --no-ansi --with dev"

      - name: "Linting: ruff check"
        run: "poetry run ruff check ."
      - name: "Linting: ruff format"
        run: "poetry run ruff format --check --diff ."

  ansible-lint:
    name: ansible-lint
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6

  documentation-lint:
    defaults:
      run:
        working-directory: ./docs
    if: needs.files-changed.outputs.documentation == 'true'
    needs: ["files-changed", "yaml-lint", "python-lint"]
    runs-on: "ubuntu-22.04"
    timeout-minutes: 5
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
        with:
          submodules: true
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: docs/package-lock.json
      - name: "Install dependencies"
        run: npm install
      - name: "Setup Python environment"
        run: "pip install invoke toml"
      - name: "Build docs website"
        run: "invoke docusaurus"

  validate-documentation-style:
    needs: ["files-changed", "yaml-lint", "python-lint"]
    runs-on: "ubuntu-22.04"
    timeout-minutes: 5
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
        with:
          submodules: true

      # The official GitHub Action for Vale doesn't work, installing manually instead:
      # https://github.com/errata-ai/vale-action/issues/103
      - name: Download Vale
        run: |
          curl -sL "https://github.com/errata-ai/vale/releases/download/v${VALE_VERSION}/\
          vale_${VALE_VERSION}_Linux_64-bit.tar.gz" -o vale.tar.gz
          tar -xzf vale.tar.gz
        env:
          VALE_VERSION: ${{ env.VALE_VERSION }}

      - name: "Validate documentation style"
        run: |
          ./vale $(find ./docs -type f \(
            -name "*.mdx" \
            -o -name "*.md" \
          \) )
