---
# yamllint disable rule:truthy
name: "Drafts your next Release notes"

on:
  workflow_call:
    inputs:
      publish:
        type: boolean
        description: Wether to publish Release note
        required: false
        default: false
      version:
        required: true
        type: string

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Tag new version
        run: |
          git tag ${{ inputs.version }}
          git push --tags

      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          publish: ${{ inputs.publish }}
          tag: ${{ inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_INFRAHUB_BOT_TOKEN }}
