---
# yamllint disable rule:truthy
name: "Run Sanity, Unit & Integration Tests"
on:
  workflow_call:
    inputs:
      runs-on:
        description: "The OS to run the job on"
        required: false
        default: "ubuntu-22.04"
        type: string
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-import:
    uses: ansible/ansible-content-actions/.github/workflows/build_import.yaml@main
  ansible-lint:
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
  sanity:
    uses: ansible/ansible-content-actions/.github/workflows/sanity.yaml@main
  # unit-galaxy:
  #   uses: ansible/ansible-content-actions/.github/workflows/unit.yaml@main
  # unit-source:
  #   uses: ansible-network/github_actions/.github/workflows/unit_source.yml@main
  #   with:
  #     collection_pre_install: >-
  #       git+https://github.com/ansible-collections/ansible.utils.git
  all_green:
    if: ${{ always() }}
    needs:
      - sanity
      - ansible-lint
      # - unit-galaxy
      # - unit-source
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert 'failure' not in
          set([
          '${{ needs.sanity.result }}',
          '${{ needs.ansible-lint.result }}'
          ])"
