---
# yamllint disable rule:truthy rule:truthy rule:line-length
name: Sync Docs Folders
on:
  workflow_call:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v5
        with:
          path: source-repo

      - name: Checkout target repository
        uses: actions/checkout@v5
        with:
          repository: opsmill/infrahub-docs
          token: ${{ secrets.GH_INFRAHUB_BOT_TOKEN }}
          path: target-repo

      - name: Sync folders
        run: |
          rm -rf target-repo/docs/docs-ansible/*
          rm -f target-repo/docs/sidebars-ansible.ts
          cp -r source-repo/docs/docs/* target-repo/docs/docs-ansible/
          cp source-repo/docs/sidebars.ts target-repo/docs/sidebars-ansible.ts
          cd target-repo
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          if ! (git diff --quiet && git diff --staged --quiet); then git commit -m "Sync docs from infrahub-ansible repo" && git push; fi
